services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: eris-sosmap-app
    working_dir: /usr/src/app/app
    ports:
      - '5173:5173'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/app/node_modules
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
